### ISSUE TITLE
Find 0 groups.

### ISSUE THREAD

**Issue by ven1996** [ShanghuoLi/pyfof#1]
--------------------------------------------------------------
-------------- statistic data points --------------
Find 0 groups.
0 points in the groups, ratio = 0/43923=0.00%
Stage-0 isolated points = 19317, ratio = 43.98%
Stage-1 isolated points (total isolated points) = 43923, ratio = 100.00%
--------------------------------------------------------------

Note:

res = fof(fitsname='velocity_cut.fits', compt=3, I0 = 0.04, dr=0.023, dv=2.13, num_min=150, dist=3400, advel=False, plot=True)

I have not used the adaptive velocity. I just followed dv = line width/(2 * beam size).

**Comment by ShanghuoLi** [comment]
I think this is because some used thresholds are too high to identify the group.  We could try it again with a relatively lower threshold.

**Comment by ven1996** [comment]
Yes, I resolved it.
